export const ONE_PAGER_TEMPLATE = {
  Objective: `In no more than two to three sentences, clearly state the purpose of this document and what it will cover. This is to help readers decide whether it's worth their time to read it.`,
  Background: `In approximately two to three paragraphs, or as long as half a page, explain why this new feature is necessary. Developers, as well as anyone reading this document, should be able to understand the progress made, the problem being solved, and the future direction by reading this section alone.`,
  Value: `Write this in list form. State briefly and clearly why each customer would "hire" the feature. List the items in order of importance, starting with number 1. For example, "Customers who know exactly what they're ordering hire this new map feature to see real-time delivery information." Typically, three to five items are listed. Having too many different customers is a sign that the PO hasn't identified the truly important customers.`,
  Principles: `List the principles that will serve as a guiding principle when making decisions during the development and presentation of this feature to customers. List them in order of importance, starting with number 1, and limit the list to six or fewer. Having too many principles is a sign of a PO's lack of simplification, so select only the most critical principles that must be adhered to. For example, a principle might be, "Customers value tracking their food delivery status the most. Therefore, we completely exclude any map features that don't help them track delivery status." Because features like satellite imagery and traffic conditions don't provide value to customers, it's helpful to establish a policy of not adding unnecessary features.`,
  Goals: `If a new feature is introduced, explain what goals will be achieved. Goals must be quantifiable. The numbers used to prove a hypothesis can be included. Typically, the number of goals should be limited to two or three. Pursuing too many goals is also a sign that the project owner has failed to prioritize.`,
  Metrics: `Select three to four metrics, including those used for your goals, that demonstrate whether the feature is fulfilling its intended purpose for your customers. If you already track metrics, you can include data from the time the document was written. This will serve as a baseline for comparing changes in metrics later. While tracking the number of customers who open and view the map might be a key metric for a new map feature in a food ordering app, monitoring changes in customer support inquiries can also be helpful. If the map is effectively informing customers about delivery status, questions like "When will it be delivered?" or "Where is it?" should decrease significantly.`,
  Roadmap: `I literally write down a development plan. I prefer to divide development into stages like "Phase 1," "Phase 2," and "Phase 3," so I list the specific tasks that need to be developed for each stage. Stage 1 is used to complete a minimum viable product (MVP) that can be tested quickly, and then stages 2 and 3 are used to refine it. Sometimes, I also divide it into short-term (within 1 month), mid- to long-term (within 3 months), and long-term (within 6 months), explaining what needs to be done for each period. If there's a feature that needs to be completed within the current quarter, it's scheduled as a short-term plan. The development plan section is reviewed by the development team or team leader and revised. At this time, the estimated time of arrival (ETA) and status are indicated. The status is marked as "Green" if there are no issues. If it's unlikely to be completed by the estimated completion date or there are issues that need to be resolved in advance, it's marked as "Yellow" or "Red." A "Red" status indicates that the item is highly unlikely to be completed.`,
  FAQ: `When developing a new feature, many questions arise not only from the development team but also from other related departments. As a product owner, it's helpful to anticipate these questions and prepare answers in advance. For example, write down a question like, "Will the new map feature be released simultaneously on both Android and iOS?" and respond with, "We'll update Android first, followed by iOS in about five weeks. Please check the development plan section for details." As with any FAQ, the format is a list. Keep in mind that repeatedly answering the same question is an inefficient use of time. Effective documentation can save you time.`,
};
